"use client";

import React from "react";
import { Card } from "../../components/ui/index.js";
import { useTools } from "../../context/ToolsContext.jsx";

export default function AuditPdfExport() {
  const { scores, findings } = useTools();

  const handlePrint = () => {
    window.print();
  };

  return (
    <Card title="Audit Report">
      <p className="text-neutral-600 dark:text-neutral-400 mb-4">
        Generate a PDF report of the current audit findings and scores.
      </p>
      <button
        onClick={handlePrint}
        className="bg-neutral-900 text-white dark:bg-white dark:text-neutral-900 px-4 py-2 rounded hover:opacity-90"
      >
        Export Pre-Production Audit (PDF)
      </button>

      {/* Hidden print-only summary */}
      <div className="hidden print:block fixed inset-0 bg-white z-50 p-8">
        <h1 className="text-3xl font-bold mb-6">
          Next.js Pre-Production Audit
        </h1>
        <div className="mb-8">
          <h2 className="text-xl font-semibold mb-2">Scores</h2>
          <div className="grid grid-cols-4 gap-4">
            <div>Performance: {scores.performance}</div>
            <div>SEO: {scores.seo}</div>
            <div>Accessibility: {scores.accessibility}</div>
            <div>Best Practices: {scores.bestPractices}</div>
          </div>
        </div>
        <div className="mb-8">
          <h2 className="text-xl font-semibold mb-2">Findings</h2>
          {findings.length === 0 ? (
            <p>No critical findings.</p>
          ) : (
            <ul className="list-disc pl-5">
              {findings.map((f, i) => (
                <li key={i}>
                  {f.module}: {f.message}
                </li>
              ))}
            </ul>
          )}
        </div>
        <div className="text-sm text-gray-500 mt-8">
          Generated by next-tools
        </div>
      </div>
    </Card>
  );
}
