"use client";

import React from "react";
import { Card, Button } from "../../components/ui/index.js";
import { useTools } from "../../context/ToolsContext.jsx";
import { Download } from "lucide-react";

export default function AuditPdfExport() {
  const { scores, findings } = useTools();

  const handlePrint = () => {
    window.print();
  };

  return (
    <Card title="Audit Report">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <p className="text-neutral-600 dark:text-neutral-400">
          Generate a PDF report of the current audit findings and scores.
        </p>
        <Button onClick={handlePrint} className="flex gap-2">
          <Download size={16} />
          Export PDF
        </Button>
      </div>

      {/* Hidden print-only summary */}
      <div className="hidden print:block fixed inset-0 bg-white z-50 p-8">
        <h1 className="text-3xl font-bold mb-6">
          Next.js Pre-Production Audit
        </h1>
        <div className="mb-8">
          <h2 className="text-xl font-semibold mb-2">Scores</h2>
          <div className="grid grid-cols-4 gap-4">
            <div>Performance: {scores.performance}</div>
            <div>SEO: {scores.seo}</div>
            <div>Accessibility: {scores.accessibility}</div>
            <div>Best Practices: {scores.bestPractices}</div>
          </div>
        </div>
        <div className="mb-8">
          <h2 className="text-xl font-semibold mb-2">Findings</h2>
          {findings.length === 0 ? (
            <p>No critical findings.</p>
          ) : (
            <ul className="list-disc pl-5">
              {findings.map((f, i) => (
                <li key={i}>
                  {f.module}: {f.message}
                </li>
              ))}
            </ul>
          )}
        </div>
        <div className="text-sm text-gray-500 mt-8">
          Generated by next-tools
        </div>
      </div>
    </Card>
  );
}
